### ISSUE TITLE
    [Errno 5] Input/output error

### ISSUE THREAD

**Issue by marianoadangelo** [aeroo/aeroo_reports#105] opened 2018-04-13 10:38 UTC
I've a server with odoo running, all was working ok but some days back aeroo reports stop working, odoo make the pdf file, but corrupt.

When I go to the config and try to connect to aerro report it says 

    Failure! Connection to DOCS service was not established or convertion to PDF unsuccessful!
    [Errno 5] Input/output error

But docs is running ok. If I stop odoo, and restart it without rebooting the server, go to Aerooreport config and configure again it connect it ok. Never need to restart docs or aeroolib nothing, only odoo server.

using Odoo 9 on debian 8.1

In the logs:

```
> 
>     2018-04-13 10:18:14,638 6411 DEBUG elfaro PIL.PngImagePlugin: STREAM IHDR 16 13
>     2018-04-13 10:18:14,639 6411 DEBUG elfaro PIL.PngImagePlugin: STREAM tEXt 41 25
>     2018-04-13 10:18:14,639 6411 DEBUG elfaro PIL.PngImagePlugin: STREAM IDAT 78 3699
>     2018-04-13 10:18:15,293 6411 INFO elfaro requests.packages.urllib3.connectionpool: Starting new HTTP connection (1): localhost
>     2018-04-13 10:18:15,327 6411 ERROR elfaro report_aeroo: Aeroo DOCS related error!
>     [Errno 5] Input/output error
>         Traceback (most recent call last):
>           File "/opt/odoo/odoo9/OCA/aeroo_reports/report_aeroo/report_aeroo.py", line 597, in create_aeroo_report
>             data = self._generate_doc(docs_client, data, report_xml, print_id, deferred)
>           File "/opt/odoo/odoo9/OCA/aeroo_reports/report_aeroo/report_aeroo.py", line 434, in _generate_doc
>             token = docs.upload(data)
>           File "/opt/odoo/odoo9/OCA/aeroo_reports/report_aeroo/docs_client_lib.py", line 101, in upload
>       self.url, data = json.dumps(payload), headers=HEADERS).json()
>       File "/opt/venv/odoo9/local/lib/python2.7/site-packages/requests/api.py", line 108, in post
>         return request('post', url, data=data, json=json, **kwargs)
>       File "/opt/venv/odoo9/local/lib/python2.7/site-packages/requests/api.py", line 50, in request
>         response = session.request(method=method, url=url, **kwargs)
>       File "/opt/venv/odoo9/local/lib/python2.7/site-packages/requests/sessions.py", line 464, in request
>         resp = self.send(prep, **send_kwargs)
>       File "/opt/venv/odoo9/local/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
>         r = adapter.send(request, **kwargs)
>       File "/opt/venv/odoo9/local/lib/python2.7/site-packages/requests/adapters.py", line 370, in send
>         timeout=timeout
>       File "/opt/venv/odoo9/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
>     
>        body=body, headers=headers)
>       File "/opt/venv/odoo9/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 349, in _make_request
>         conn.request(method, url, **httplib_request_kw)
>       File "/usr/lib/python2.7/httplib.py", line 1039, in request
>         self._send_request(method, url, body, headers)
>       File "/usr/lib/python2.7/httplib.py", line 1073, in _send_request
>         self.endheaders(body)
>       File "/usr/lib/python2.7/httplib.py", line 1035, in endheaders
>         self._send_output(message_body)
>       File "/usr/lib/python2.7/httplib.py", line 879, in _send_output
>         self.send(msg)
>       File "/usr/lib/python2.7/httplib.py", line 846, in send
>         print "send:", repr(data)
>     IOError: [Errno 5] Input/output error
>     2018-04-13 10:18:15,332 6411 INFO elfaro report_aeroo: End process report.aeroo_report_ar_sale_order (sale.order), elapsed time: 1.26793503761
> 
```

**Comment by sraps** [comment] 2018-04-14 09:03
Is the DOCS server running on separate machine?

**Comment by sraps** [comment] 2018-04-14 09:16
2018-04-13 10:18:15,293 6411 INFO elfaro requests.packages.urllib3.connectionpool: Starting new HTTP connection (1): localhost

Oh, I see it is localhost

**Comment by sraps** [comment] 2018-04-14 09:46
If we're looking around the code of httplib.py at line 781 (presumably a bit different version of httplib, because your setup states line 846), it has something to do with the debug. Which in turn, most likely, does not have correct standard output to do a print somewhere, so it does produce IO error.
https://github.com/enthought/Python-2.7.3/blob/master/Lib/httplib.py#L781

I am not familiar what enables debug of the httplib.py HTTPConnection object, and even more why it happens from time to time, and not all the time.

**Comment by marianoadangelo** [comment] 2018-04-14 13:32
could debug the moment when the report fails

```
2018-04-14 13:07:47,764 6570 DEBUG plastimac PIL.PngImagePlugin: STREAM IHDR 16 13
2018-04-14 13:07:47,764 6570 DEBUG plastimac PIL.PngImagePlugin: STREAM tEXt 41 25
2018-04-14 13:07:47,764 6570 DEBUG plastimac PIL.PngImagePlugin: STREAM IDAT 78 3699
2018-04-14 13:07:47,772 6570 DEBUG plastimac PIL.PngImagePlugin: STREAM IHDR 16 13
2018-04-14 13:07:47,772 6570 DEBUG plastimac PIL.PngImagePlugin: STREAM pHYs 41 9
2018-04-14 13:07:47,772 6570 DEBUG plastimac PIL.PngImagePlugin: STREAM iTXt 62 14830
2018-04-14 13:07:47,773 6570 DEBUG plastimac PIL.PngImagePlugin: STREAM cHRM 14904 32
2018-04-14 13:07:47,773 6570 DEBUG plastimac PIL.PngImagePlugin: cHRM 14904 32 (unknown)
2018-04-14 13:07:47,773 6570 DEBUG plastimac PIL.PngImagePlugin: STREAM IDAT 14948 31328
2018-04-14 13:07:47,883 6570 INFO plastimac requests.packages.urllib3.connectionpool: Starting new HTTP connection (1): localhost
2018-04-14 13:07:47,885 6570 ERROR plastimac report_aeroo: Aeroo DOCS related error!
[Errno 32] Broken pipe
Traceback (most recent call last):
  File "/opt/odoo/odoo9/OCA/aeroo_reports/report_aeroo/report_aeroo.py", line 597, in create_aeroo_report
    data = self._generate_doc(docs_client, data, report_xml, print_id, deferred)
  File "/opt/odoo/odoo9/OCA/aeroo_reports/report_aeroo/report_aeroo.py", line 434, in _generate_doc
    token = docs.upload(data)
  File "/opt/odoo/odoo9/OCA/aeroo_reports/report_aeroo/docs_client_lib.py", line 101, in upload
    self.url, data = json.dumps(payload), headers=HEADERS).json()
  File "/opt/venv/odoo9/local/lib/python2.7/site-packages/requests/api.py", line 108, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/opt/venv/odoo9/local/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/opt/venv/odoo9/local/lib/python2.7/site-packages/requests/sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/venv/odoo9/local/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/opt/venv/odoo9/local/lib/python2.7/site-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/opt/venv/odoo9/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/opt/venv/odoo9/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 349, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 1039, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1073, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1035, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 879, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 846, in send
    print "send:", repr(data)
IOError: [Errno 32] Broken pipe
2018-04-14 13:07:47,887 6570 INFO plastimac report_aeroo: End process report.aeroo_report_ar_sale_order (sale.order), elapsed time: 0.762506008148
Traceback (most recent call last):
  File "/opt/odoo/odoo9/OCA/aeroo_reports/report_aeroo/report_aeroo.py", line 597, in create_aeroo_report
    data = self._generate_doc(docs_client, data, report_xml, print_id, deferred)
  File "/opt/odoo/odoo9/OCA/aeroo_reports/report_aeroo/report_aeroo.py", line 434, in _generate_doc
    token = docs.upload(data)
  File "/opt/odoo/odoo9/OCA/aeroo_reports/report_aeroo/docs_client_lib.py", line 101, in upload
    self.url, data = json.dumps(payload), headers=HEADERS).json()
  File "/opt/venv/odoo9/local/lib/python2.7/site-packages/requests/api.py", line 108, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/opt/venv/odoo9/local/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/opt/venv/odoo9/local/lib/python2.7/site-packages/requests/sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/venv/odoo9/local/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/opt/venv/odoo9/local/lib/python2.7/site-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/opt/venv/odoo9/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/opt/venv/odoo9/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 349, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 1039, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1073, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1035, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 879, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 846, in send
    print "send:", repr(data)
IOError: [Errno 32] Broken pipe
2018-04-14 13:07:47,888 6570 INFO plastimac report_aeroo: End total process report.aeroo_report_ar_sale_order (sale.order), total elapsed time: 0.774438142776
None
```
after the broken pipe error, it stay down until I restart odoo and configure again aeroo report from config menu. If I try yo re-config odoo without restart i get the IOError: [Errno 5] Input/output error

**Comment by sraps** [comment] 2018-04-14 14:09
That error is unrelated to the cause. Somehow it can not print debug info to the standard output. First of all it could happen when Odoo is in debug mode, set in Odoo configuration. Ok, probably it is possible to tweak the Aeroo DOCS code by setting debug parameter to False. But that is awkward.

IMHO this error would not fire in Odoo with debug mode switched on, and command line interactive mode. Or service mode with debug switched off. It seems that it is loosely connected with Aeroo, but rather httplib, that is unable to work properly without standard output.

**Comment by marianoadangelo** [comment] 2018-04-14 20:58
you advice me to change my httplib version to the one you pointed?
I dont know how to fix this...

**Comment by sraps** [comment] 2018-04-15 07:18
Although, it is always best to start with, still I do not think it will make the difference. Check if you have the debug mode enabled in Odoo configuration. If yes, disable it and test the result.

**Comment by marianoadangelo** [comment] 2018-04-15 15:39
Debug mode is off in odoo config.
I increase PostgreSQL workers and set odoo logrotate to true, and log level
to warn.

I think postgres reject the connection and them crash aeroo report. It has
been working for 16 hs.

**Comment by sraps** [comment] 2018-04-15 15:44
Might be. Meanwhile I am closing this issue, feel free to reopen it...

**Closed as completed by sraps** 2018-04-15 15:44 UTC
